/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Graphics;
import java.util.ArrayList;
import java.awt.PointerInfo;
import java.awt.Point;
/**
 *
 * @author 340826148
 */
public class DrawingArea extends javax.swing.JPanel {
Timer tl;
public static int sLeft = 50;
public  static int sRight = 600;
public static int sTop = 10;
public static int sBottom = 500;
Ball ballA;
Color[] mCol = new Color[6];
ArrayList<Ball> theBall = new ArrayList<>();
int curC = 0;

    /**
     * Creates new form DrawingArea
     */
    public DrawingArea() {
        initComponents();
        ballA = new Ball(100,200,mCol[curC]);
        tl = new Timer(50, new DrawingArea.TimerListener());
        tl.start();
        mCol[0] = new Color(255, 0, 0);
        mCol[1] = new Color(0,255,0);
        mCol[2] = new Color(0,0,255);
        mCol[3] = new Color(255,0,255);
        mCol[4] = new Color(0,0,0);
        mCol[5] = new Color(250,161,6);
    }

    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        for(int i = 0; i<=theBall.size() - 1;i++){
            g.setColor(theBall.get(i).getBallColor());
            g.fillOval(theBall.get(i).setBallX(), theBall.get(i).setBallY(),20,20);
        }

        
    }
    
    private class TimerListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            repaint();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        
        int x = (int)b.getX();
        int y = (int)b.getY();
        theBall.add(new Ball(x,y,mCol[curC]));
        curC++;
        if(curC>5){
            curC = 0;
        }
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
